eureka:
  instance:
    instance-id: ${spring.application.name}:${random.uuid}
    hostname: localhost
  client:
    serviceUrl:
      #defaultZone: http://164.52.202.187:8761/eureka/
      defaultZone: http://localhost:8080/eureka/
server:
  port: 8001
ribbon:
  eureka:
    enabled: false  
spring:
  application:
    name: api-gateway
  cloud:
    loadbalancer:
      ribbon:
        enabled: false
    discovery:
      enabled: true
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
      - id: eChallan-user-service
        uri: lb://eChallan-user-service
        #uri: http://localhost:8081
        predicates:
        - Path=/user/**